module.exports = [
    'Quando você nasceu, ainda que por apenas alguns segundos, você foi a pessoa mais jovem do planeta.',
    'As aranhas são incapazes de voar.',
    'Na Suécia existe uma competição de saltos de obstáculos para coelhos.',
    'As tartarugas também podem respirar através de seus traseiros.',
    'Os Beatles usaram a palavra “Love” — ou “Amor” em inglês — 613 vezes em suas canções.',
    'Existem macacos no Japão que usam moedas para comprar petiscos em máquinas de conveniência.',
    'As lontras-marinhas dormem de “mãozinhas” dadas para não correrem o risco de se afastarem umas das outras.',
    'Um pinguim foi nomeado Cavaleiro Honorário da Guarda do Rei da Noruega.',
    'Na China, se alguém matar um urso panda pode ser sentenciado à morte.',
    'Quando estamos beijando, queimamos duas calorias por minuto.',
    'No Butão, existe um importante indicador social chamado “Felicidade Interna Bruta”',
    'Pesquisadores descobriram que as vacas produzem mais leite quando estão ouvindo músicas tranquilas, especialmente quando ouvem “Everybody Hurts” da banda R.E.M.',
    'Os esquilos plantam milhares de árvores todos os anos por acidente, simplesmente porque se esquecem de onde enterram suas sementes.',
    'O casal de dubladores que interpretavam os personagens Mickey e Minie Mouse se casou na vida real.',
    'A Tabela Periódica, o Google, a estrutura do DNA e a música “Yesterday” dos Beatles, foram todas ideias que foram concebidas durante os sonhos de seus criadores.',
    'Sabia que o nome de Edson Arantes do Nascimento, o nosso Rei Pelé, é uma homenagem a Thomas Edison?',
    'Os antigos gregos se recusavam a comer feijões por acreditar que os grãos continham as almas dos mortos.',
    'O dramaturgo inglês Shakespeare e Pocahontas, a nativa norte-americana que inspirou o surgimento de inúmeros mitos e filmes, viveram na mesma época.',
    'Os primeiros transplantes de órgãos de que se têm registro aconteceram por volta do ano de 800 a.C., quando médicos indianos começaram a usar enxertos de pele para curar ferimentos.',
    'As melancias contêm uma substância chamada citrulina, que pode desencadear a produção de um composto que ajuda a relaxar os vasos sanguíneos e tem ação parecida à do Viagra.',
    'O Burj Khalifa, famoso arranha-céu edificado em Dubai, é tão alto que os residentes que vivem acima do 80º andar finalizam o Ramadan entre 2 e 3 minutos depois que os demais muçulmanos.',
    'Sabia que os tigres podem e — se tiverem oportunidade — vão se vingar daqueles que algum dia os maltrataram?',
    'No ano de 2010, a Síria recebeu mais turistas do que a Austrália.',
    'Na década de 50, um cientista trouxe abelhas africanas (Apis mellifera scutellata) aqui para o Brasil e deixou que algumas escapassem acidentalmente. Elas acabaram acasalando com as abelhas europeias e dando origem às híbridas abelhas africanizadas — as mais agressivas, perigosas e mortais do planeta.',
    'Cientistas estimaram que as temperaturas no local onde a bomba de Hiroshima explodiu chegaram a extraordinários 300 mil graus Célsius — isto é, cerca de 300 vezes mais quente do que a temperatura com a qual os corpos humanos normalmente são cremados.',
    'No ano de 117, o Imperador Romano Adriano decretou que a tentativa de suicídio entre soldados era uma forma de deserção e, portanto, devia ser punida com morte.',
    'Entre os anos de 2001 e 2015, de todas as mortes ocorridas por conta de ataques terroristas, 75% foram contabilizadas em países de maioria muçulmana e apenas 2,2% do total na Europa e nos Estados Unidos.',
    'Aliás, já que estamos no assunto, de acordo com o FBI, 94% dos ataques terroristas perpetrados nos EUA entre 980 e 2005 foram realizados por não muçulmanos.',
    'As folhinhas dos morangos têm ação medicinal. Além de servir para aliviar dores nas juntas e problemas gastrointestinais, elas são ricas em cálcio, ferro e vitamina C.',
    'O escritor francês Guy de Maupassant detestava tanto a Torre Eiffel — ele a chamava de estrutura monstruosa e inútil —, que costumava comer no restaurante instalado em sua base, uma vez que esse era o único lugar de onde ele não era obrigado a olhar para a construção.',
    'A pele dos elefantes pode chegar a ter mais de 2,5 centímetros de espessura. No entanto, ela é tão sensível que os paquidermes são capazes de sentir quando uma mosquinha pousa sobre eles.',
    'Em 2005, um economista e um psicólogo decidiram ensinar a um grupo de macacos o conceito de dinheiro. Para a surpresa dos pesquisadores, não demorou até que os primatas começassem a se envolver com a prostituição.',
    'Os olhos humanos são capazes de detectar a chama de uma vela a quase 2,8 quilômetros de distância.',
    'E já que estamos falando de olhos, enquanto as borboletas têm quatro, as abelhas cinco e a maioria das aranhas oito, as lagartas contam com doze olhos.',
    'Sabia que as penas das aves pesam mais do que seus esqueletos?',
    'Depois de dissecar cadáveres humanos, Leonardo da Vinci costumava substituir os músculos por barbantes para estudar seu funcionamento.',
    'Pequim é a cidade com os aluguéis mais altos do mundo. Segundo um levantamento feito no ano passado, o valor do aluguel de uma residência é, em média, 1,2 vez mais alto do que os salários médios que as pessoas recebem.',
    'O termo “ariano” é originário da Pérsia e significa “nobre”. Ele foi adotado mais tarde pelos defensores do nazismo em referência a sua “raça superior”.',
    'Um estudo apontou que os gatos amam seus donos de maneira diferente que os cães. Testes revelaram que os cérebros dos cachorros liberam oxitocina — o famoso hormônio do amor — em quantidades muito maiores do que os dos felinos.',
    'Os antigos egípcios usavam um calendário composto por 12 meses com exatamente trinta dias cada — e, para que o ano somasse 365 dias, eles adicionavam cinco dias de festividades ao final.',
    'Durante a Lei Seca dos EUA, os contrabandistas usavam "sapatos de vaca" para não deixarem rastros para a polícia.',
    'A Guinness (marca de cerveja) estima que 93 mil litros de cerveja são perdidos em pelos faciais a cada ano apenas no Reino Unido.',
    'Alguns gatos são alérgicos a humanos.',
    'A Volvo liberou em 1962 a patente do cinto de segurança de três pontos para salvar vidas.',
    'Tsundoku é o ato de adquirir livros e não lê-los.',
    'Corvos em cativeiro pode aprender a falar melhor que papagaios.',
    'O ator Bela Lugosi foi enterrado junto com o traje compledo do Drácula.',
    'Existem pelo menos 10 lojas Blockbuster (locadora de filmes) que ainda funcionam nos EUA. Na sua cidade tem alguma?',
    'Os doadores de sangue na Suécia recebem um texto de agradecimento quando o sangue deles é usado.',
    'Estima-se que 1 milhão de cães nos EUA tenham sido nomeados como beneficiários primários de heranças deixadas por seus donos.',
    'Os russos chegaram 12 dias atrasados para as Olímpiadas de Londres em 1908 pois eles usam o calendário juliano e nçao o gregoriano.',
    'Para os japoneses, deixar um lutador de sumô fazer um bebê chorar é sinal de sorte.',
    'Portland foi nomeado através do cara ou coroia. Se a moeda tivesse caído do outro lado, a cidade seria se chamaria Boston.',
    'Se os motoristas dirigirem na velocidade correta na rodovia Rote 66 no Novo México, faixas sonoras começam a tocar uma versão de "America the Beautiful".',
    'Cosmonautas russos costumavam levar uma espingarda para caso pousassem na Sibéria pudessem se defender dos ursos.',
    'O número anual de mordidas de tubarão em todo o mundo é 10 vezes menor do que o número de pessoas mordidas por outras pessoas em Nova York.',
    'Os cães são capazes de entender até 250 palavras e gestos dos humanos. Um cachorro é tão inteligente quanto uma criança de dois anos.',
    'Peter Durand patenteou a lata em 1810. Ezra Warner patenteou um abridor de latas em 1858. Entre esse tempo as pessoas usavam martelos e cinzéis para abrir as latas.',
    'As cabras tem pupilas retangulares.',
    'Na França é ilegal que os supermercados desperdicem alimentos. Eles devem doar as mercadorias que não foram vendidas.',
    'Fredric Baur inventou a lata de Pringles. Quando ele faleceu em 2008, suas cinzas foram enterradas em uma.',
    'Um bebê pode custar aos pais 750 horas de sono só no primeiro ano.',
    'Susan B. Anthony foi multada em 100 dólares por votar nas eleições americanas de 1872. Ela nunca pagou a multa.',
    'Harrison Schmitt, astronauta da Apollo 17 , era alérgico ao pó da lua.',
    'Um episódio de Peppa Pig foi retirado da televisão australiana porque ensinava as crianças a não terem medo de aranhas.',
    'Em 1967, a guerra civil nigeriana parou por dois dias pois os dois lados queriam ver Pelé jogando.',
    'Na Suíça, é ilegal possuir apenas uma cobaia. Esses animais se reproduzem em uma velocidade impressionante.',
    'Rainha Elizabeth II teve mais de 30 cães da raça Coegi em sua vida.',
    'Em relação a seus corpos, os chihuahuas tem o maior cérebro do mundo canino.',
    'Em 2014, o Tinder teve seu primeiro Match na Antártida. Ambas as partes envolvidas eram cientistas.',
    'Há uma estátua de Nikola Tesla em Palo Alto que oferece acesso Wi-Fi gratuito.',
    'Frank Sinatra tem três estrelas na Calçada da Fama de Hollywood: uma para cinema, uma para música e outra para televisão.',
    'No dia 1º de abril de 1930, a BBC informou que não havia notícias. Em vez disso eles tocaram músicas de piano.',
    'As tarântulas gigantes costumam manter pequenos sapos em sua toca para proteger seus ovos. Os sapinhos se alimentam de insetos minúsculos e impedem que comam os ovinhos da aranha, que prefere presas maiores.',
    'Talvez não seja alucinante, mas às vezes os cães e lobos que participam de filmes precisam de rabos CGI (imagens geradas por computador). A empolgação dos animais é tanta, que mal conseguem parar de mexer seus rabos.',
    'Na Suíça, é proibido por lei possuir apenas um porquinho-da-índia de estimação. Se pretende criar o animal em casa, precisará ter pelo menos dois para que não se sintam solitários.',
    'As lontras marinhas dão as mãos quando dormem para não flutuarem para longe e possuem uma pedra favorita que guardam em uma bolsa secreta. Elas podem viver a vida toda carregando a mesma pedra.',
    'Quando aquecemos um imã ele perde suas propriedades magnéticas.',
    'Os cães podem sentir quando você está voltando para casa só pelo cheiro de seu perfume.',
    'As vacas possuem “melhores amigas” e ficam estressadas quando são separadas.',
    'Os seres humanos são bioluminescentes e brilham! Mas a luz que emitimos é mil vezes mais fraca do que nossos olhos podem enxergar.',
    'Touros não se irritam com a cor vermelha.',
    ' Elefantes pesam em média o mesmo que a língua de uma baleia azul.',
    'O cocô do Vombate (animal nativo da Austrália), é em forma de cubo.',
    'O nome do Ártico vem da palavra grega antiga arktos (que significa urso). O nome é referente às constelações Ursa Maior e Ursa Menor que apontam no norte do planeta. Então, basicamente, o Ártico é chamado de “Urso”, e o Antártico é chamado de “Não Urso”.',
    'Tigres têm pele listrada! Não são só os pêlos.',
    'O unicórnio é o animal símbolo nacional da Escócia.',
    'O edifício com mais banheiros no mundo, é o estádio de Wembley.',
    'Arco-íris é na verdade um círculo-íris.',
    'Desde o momento em que Plutão foi descoberto até o momento em que foi desconsiderado um planeta, ele ainda não havia feito uma volta completa em torno do sol.',
    'Quando um gato caminha em sua direção com o rabo para cima, significa que ele gosta de você e está feliz em vê-lo.',
    'Quando uma abelha é escolhida para ser a nova rainha, ela recebe um tipo especial de mel que muda completamente seu corpo. É como a evolução de um Pokémon.',
    'Um dia em Vênus é mais longo do que um ano no mesmo. O planeta simplesmente leva mais tempo para fazer uma rotação completa em torno de seu eixo, do que para girar em torno do sol.',
    'As abelhas reproduzem uma espécie de dança para avisar aos amigos sobre a existência de boas flores no local.',
    'Haviam mamutes lanosos na Terra quando as pirâmides estavam sendo construídas.',
    'Antes de 1914, nos EUA, os pais podiam enviar seus filhos para a casa dos avós pelos correios.',
    'As lagostas eram consideradas comida repugnante e de classe baixa. Eram usadas para alimentar prisioneiros como forma de punição cruel. Além disso, a iguaria é basicamente uma grande barata do mar.',
    'O ronronar (espécie de rugido dos gatinhos), de um gato melhora sua densidade e estrutura óssea.',
    'Os baiacus estão cheios de água, não de ar.',
    'O chocolate já foi usado como moeda de troca pela civilização maia.',
    'Um filhote de panda nasce tão pequeno quanto um rato.',
    'No Japão, existe uma ilha povoada por coelhos!',
    'O diâmetro da lua é 400 vezes menor que o do sol, porém, o sol está cerca de 400 vezes mais distante. Por conta disso, podemos ter eclipses solares e lunares.',
    'Na Itália, existe um banco com “poupança” de queijo.',
    'As pirâmides já eram bem antigas quando Cleópatra estava por perto.',
    'Muitos dos vídeos de TV ou Internet vêm através de cabos submarinos',
    'O coração de uma baleia azul é tão grande quanto um Fusca.',
    'Lontras marinhas têm bolsos de pele para guardar suas pedras favoritas.',
    'Existe o termo “Debug com pato de borracha” (rubberducking), usado pelos programadores para ajudá-los a encontrar erros. A prática de descrever o problema para um “pato de borracha”, os ajudam a encontrar uma solução.',
    
]